#!/bin/sh

echo -n "Building math program..."
echo

rm a.out

gcc dot_product.c dot_product.h gram-schmidt-ort-proc.c gram-schmidt-ort-proc.h main.c main.h matrix.c matrix.h file_managing.c file_managing.h gen_matrix.c gen_matrix.h menu.c menu.h -Wall -lm -g -fsanitize=leak -fsanitize=undefined 

echo -n "Building completed"
echo

sleep 1

clear

./a.out

sleep 1

clear
